# Generated by Django 3.0.4 on 2020-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('about', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
