# Generated by Django 3.0.4 on 2020-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_desc', models.TextField()),
                ('event_status', models.CharField(max_length=50)),
                ('event_cover', models.ImageField(default='event_covers/default.jpg', upload_to='event_covers/')),
                ('event_type', models.CharField(choices=[('technical', 'TECHNICAL'), ('non-technical', 'NON-TECHNICAL')], max_length=20)),
                ('event_rules', models.TextField()),
                ('event_participants', models.IntegerField()),
                ('event_organizer', models.TextField()),
                ('event_winners', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnos', models.CharField(max_length=100)),
                ('reg_events', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
