# Generated by Django 3.0.4 on 2020-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200312_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_participants',
            new_name='no_of_participants',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_organizer',
            new_name='organizer',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_rules',
            new_name='rules',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_winners',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='winners',
            field=models.TextField(blank=True),
        ),
    ]
