# Generated by Django 3.0.4 on 2020-03-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200312_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizers',
        ),
    ]
